Feature/user login
emasdigi/OnboardingUserService pull request #2
Opened 2021-07-13 08:05 UTC by jenil123

Added code for user login service
Added code for forgot password feature

2021-07-13 12:11 UTC, bhautikgosai96 commented
Hi Jenil,

Remove variable attempts as you are not using it and also parameters HttpServletRequest request, HttpServletResponse response from loginUser PostMapping as they are also not used.

2021-07-13 12:29 UTC, bhautikgosai96 requested changes
Hi Jenil,

- Remove variable attempts as you are not using it and also parameters HttpServletRequest request, HttpServletResponse response from loginUser PostMapping as they are also not used.
- In ResetPassword model request class add annotation @DaTa so we don't need to write getter/setters and if you need to write constructor add annotation @AllArgsConstructor and remove getter/setters/constructor. Do same changes in userLogin model request class also.
- As you have made request model, same way make response model, as your are just returning string, make message for particular response message and other fields if require. you can refer same in my code.
- Remove System.out.println() from userservice class.

2021-07-13 12:43 UTC, jenil123 commented
> Hi Jenil,
> 
> * Remove variable attempts as you are not using it and also parameters HttpServletRequest request, HttpServletResponse response from loginUser PostMapping as they are also not used.
> * In ResetPassword model request class add annotation @DaTa so we don't need to write getter/setters and if you need to write constructor add annotation @AllArgsConstructor and remove getter/setters/constructor. Do same changes in userLogin model request class also.
> * As you have made request model, same way make response model, as your are just returning string, make message for particular response message and other fields if require. you can refer same in my code.
> * Remove System.out.println() from userservice class.


Hi Bhautik,
As per the suggestions I have changed the code for request package and added a response package for meaningful responses. Please review the same. 

Thanks 
Jenil

2021-07-14 18:20 UTC, ankit2204 commented on src/main/java/com/pluang/OnboardingUserService/service/UserService.java
> +    public UserResponse isCorrect(UserLogin loginInfo) throws NoSuchAlgorithmException {
We should use a better name for this function like validateUserLogin.

2021-07-14 18:20 UTC, ankit2204 commented on src/main/java/com/pluang/OnboardingUserService/service/UserService.java
> +    public boolean checkIfBlocked(String mobNumber)
This is a good implementation, but we should not keep track of these attributes in memory, by doing that we are making our service stateful.
Problem with that is, suppose we have multiple instances of user service, every request will be routed to a different instance and our checks will fail because other instances are not sharing this information. 

Correct way to implement these use cases will be using Spring Security, Go through the documentation of spring security.

2021-07-15 05:01 UTC, aditya-jha requested changes

2021-07-15 05:01 UTC, aditya-jha commented on src/main/java/com/pluang/OnboardingUserService/entities/User.java
> +@AllArgsConstructor
why do you need all args constructor?

2021-07-15 05:01 UTC, aditya-jha commented on src/main/java/com/pluang/OnboardingUserService/controller/UserController.java
> +    public UserResponse postUserInfo(@RequestBody UserLogin loginInfo) throws NoSuchAlgorithmException {
postUserInfo sounds more like you are posting details of a new user. Fix the name

2021-07-15 08:53 UTC, jenil123 commented
Hi Aditya and Ankit, 
I have changed the code as per the suggestions. I have used spring security for checking if user is logged In or not. And used a separate table for keeping track of unsuccessful login attempts.

2021-07-16 04:29 UTC, ankit2204 approved these changes

2021-07-16 04:39 UTC, merged